// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwv8xRQIwBKeM_LszpU_RtEIL220Tk13c',
    appId: '1:198627159024:web:1be3668e0ae7e86288cb35',
    messagingSenderId: '198627159024',
    projectId: 'acadinsight-4b38b',
    authDomain: 'acadinsight-4b38b.firebaseapp.com',
    storageBucket: 'acadinsight-4b38b.firebasestorage.app',
    measurementId: 'G-SJJRZTVKCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD_KwF96hrWcI3gk5KbJQtkU4uk18ABb4',
    appId: '1:198627159024:android:48585951f7d80d8b88cb35',
    messagingSenderId: '198627159024',
    projectId: 'acadinsight-4b38b',
    storageBucket: 'acadinsight-4b38b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBcdhRH-E8QGFA3O0jnHUI1CWTadH3Tk',
    appId: '1:198627159024:ios:b4b97cf2d354309288cb35',
    messagingSenderId: '198627159024',
    projectId: 'acadinsight-4b38b',
    storageBucket: 'acadinsight-4b38b.firebasestorage.app',
    iosBundleId: 'com.example.academicSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBcdhRH-E8QGFA3O0jnHUI1CWTadH3Tk',
    appId: '1:198627159024:ios:b4b97cf2d354309288cb35',
    messagingSenderId: '198627159024',
    projectId: 'acadinsight-4b38b',
    storageBucket: 'acadinsight-4b38b.firebasestorage.app',
    iosBundleId: 'com.example.academicSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwv8xRQIwBKeM_LszpU_RtEIL220Tk13c',
    appId: '1:198627159024:web:e9da2bca5b0c19de88cb35',
    messagingSenderId: '198627159024',
    projectId: 'acadinsight-4b38b',
    authDomain: 'acadinsight-4b38b.firebaseapp.com',
    storageBucket: 'acadinsight-4b38b.firebasestorage.app',
    measurementId: 'G-W71PLC2FTG',
  );
}
